name: deepfake-detection
channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.10
  - pip>=21.0
  
  # Core scientific computing
  - numpy>=1.21.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  
  # Computer vision
  - opencv>=4.5.0
  
  # Deep learning (CPU version, use separate install for GPU)
  - pytorch::pytorch>=1.9.0
  - pytorch::torchvision>=0.10.0
  - pytorch::cpuonly  # Remove this line for GPU support
  
  # Utilities
  - matplotlib>=3.4.0
  - pandas>=1.3.0
  - tqdm>=4.62.0
  - requests>=2.26.0
  
  # Development
  - jupyter>=1.0.0
  - ipython>=7.27.0
  - pytest>=6.2.0
  
  # Pip packages not available in conda
  - pip:
    - timm>=0.6.0
    - facenet-pytorch>=2.5.2
    - onnx>=1.12.0
    - onnxruntime>=1.12.0
    - kaggle>=1.5.12
    - albumentations>=1.1.0

# Usage:
# conda env create -f environment.yml
# conda activate deepfake-detection
